//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation.UserControls
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Facturation_DBEntities2 : DbContext
    {
        public Facturation_DBEntities2()
            : base("name=Facturation_DBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINN> ADMINN { get; set; }
        public virtual DbSet<APPEL> APPEL { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<CODE_ERREUR> CODE_ERREUR { get; set; }
        public virtual DbSet<CODE_REPARATION> CODE_REPARATION { get; set; }
        public virtual DbSet<FACTURATION> FACTURATION { get; set; }
        public virtual DbSet<INGENIEUR> INGENIEUR { get; set; }
        public virtual DbSet<PIECE> PIECE { get; set; }
        public virtual DbSet<REPARATION> REPARATION { get; set; }
        public virtual DbSet<SECRETAIRE> SECRETAIRE { get; set; }
        public virtual DbSet<TYPE_APPEL> TYPE_APPEL { get; set; }
        public virtual DbSet<VILLE> VILLE { get; set; }
    }
}
