//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPEL()
        {
            this.FACTURATIONs = new HashSet<FACTURATION>();
            this.TYPE_APPEL = new HashSet<TYPE_APPEL>();
        }
    
        public int IdAppel { get; set; }
        public Nullable<System.DateTime> DateEtHeurAppel { get; set; }
        public string IdClient_ { get; set; }
        public string DescriptionAppel { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURATION> FACTURATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TYPE_APPEL> TYPE_APPEL { get; set; }
    }
}
