//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURATION()
        {
            this.CODE_ERREUR = new HashSet<CODE_ERREUR>();
        }
    
        public int IdFacture { get; set; }
        public Nullable<int> IdReparation_ { get; set; }
        public Nullable<int> IdAppel_ { get; set; }
        public Nullable<bool> EstImprime { get; set; }
    
        public virtual APPEL APPEL { get; set; }
        public virtual REPARATION REPARATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODE_ERREUR> CODE_ERREUR { get; set; }
    }
}
