//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Facturation_DBEntities : DbContext
    {
        public Facturation_DBEntities()
            : base("name=Facturation_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINN> ADMINNs { get; set; }
        public virtual DbSet<APPEL> APPELs { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<CODE_ERREUR> CODE_ERREUR { get; set; }
        public virtual DbSet<CODE_REPARATION> CODE_REPARATION { get; set; }
        public virtual DbSet<FACTURATION> FACTURATIONs { get; set; }
        public virtual DbSet<INGENIEUR> INGENIEURs { get; set; }
        public virtual DbSet<PIECE> PIECEs { get; set; }
        public virtual DbSet<REPARATION> REPARATIONs { get; set; }
        public virtual DbSet<SECRETAIRE> SECRETAIREs { get; set; }
        public virtual DbSet<TYPE_APPEL> TYPE_APPEL { get; set; }
        public virtual DbSet<VILLE> VILLEs { get; set; }
    }
}
